### ISSUE TITLE
Addition of all software on computer, ready for cloning

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-Survey-Planning#6]
Megsie notes for this year and next:
- This is for all survey computers (Metis computer, wheelhouse).
- The software list includes our data collection software (Metis, Wheelhouse/Calypso, Scanmenu, Hoboware, Globe, Portfolio and more) as well peripheral softwares (e.g., BVDRconverter, SunriseSunset, Station Dropping Tool, Basket Counting Spreadsheet, etc.). Usually the peripheral software stays on the survey computers from the previous years and gets cloned, so this task just entails making sure the right versions are there and that they work as expected. 
- In addition to the [list of software on the Survey App](file://akc0ss-n086/RACE_GF/RACE_Survey_App/docs/software_software_&_drivers.html), we need to make sure Metis computers have updates to GAPSurvey R package and Metis, and that there is a working version of Wildlife Computers on the wheelhouse or marport machine for importing the light data.

# All computers (I think)
[HP1006 Printer drivers](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/HP1006_drivers)

# Metis computer
## Basics
- MS Office or [File format converter (docx xlsx)](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/docx_xlsx_file_converter)
- [HP1006 Printer drivers](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/HP1006_drivers) - to check, go to Printers and Devices in Settings. Scroll down to Related Settings and select Print server properties. Select the Drivers tab, and see if your printer is listed. If it is, you’re all set. Sarah and I installed this on the Metis computer for cloning based on the Survey App. Need to plug into printer to complete install?

## CTD data and data processing
- SBE Data Processing
- SeaTerm
- SeaView

# Wheelhouse computer
- [HOBO Lite 3.7.8](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/Bottom%20contact%20sensor)
- [BVDR Converter](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/BVDR_converter/)
- [Hyperterm](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/Hyperterm) ?? for communicating w serial devices.
- [Light Meters](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/Light%20meters) (also **Marport computer**)
- Working version of Wheelhouse
- Calypso
- ArcMap with the survey area map of trawlable/untrawlable stations
- MS Office suite (Excel, Word, and Access).
- "Single file" tools like Station Dropping Tool, Net spreadsheets from Shawn, anything else?

# Marport computer
- [Light Meters](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/Light%20meters)
- [SiRFDemo](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/GPSs) (for configuring GPS thru serial port)
- CommandView
- Commander (Paul thinks Marport Server is part of Commander, but check with Gary M to make sure).

# Unknown
- [Network Time Sync](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/NetWork%20Time%20sync)
-  DEPRECATED: [Post Cruise Migration (v.20190517)](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/Data)

# Globe computer
- Globe
- [SiRFDemo](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/GPSs)
- [Tides and Currents](https://github.com/orgs/afsc-gap-products/projects/4/files/Manuals/Tides%20and%20Currents) (possibly deprecated?)

**Comment by Ned-Laman-NOAA** [comment]
Make sure that we have a working Wildlife Computers software suite on bridge computers (preferred) and maybe even on the Metis computers for a back up.

**Comment by Ned-Laman-NOAA** [comment]
This is pretty straightforward and I've done it before. We need more people to know how to do it so let's see if this team can take this on. If we have the Wildlife Computers software working on the bridge computer and back up that should suffice.

**Comment by bethanyriggle** [comment]
Gary usually handles this, but I can make sure it is on the necessary computers since I have handled installing it before.

**Comment by Ned-Laman-NOAA** [comment]
If we get this on the master computer that Gary clones, this takes care of itself.

**Comment by MargaretSiple-NOAA** [comment]
For this task, we will at least need to:
- Make sure Metis version is the most updated one
- Update the GAPSurvey package version to the most recent version (last updated this past week) 
 
There may be other changes as well!

**Comment by MargaretSiple-NOAA** [comment]
I believe all the software checking is done from our side for the Metis computer. We did the following:
- connect tablets via bluetooth using BlueSoleil / Bluetooth Explorer
- transfer raw metis data files
- import into metis and edit in GIDES
- export biological data 
- backup database

A couple optional things we could do but didn't:
- install driver for HP 1006 (needed to plug directly into printer, which we didn't have)
- test CTD data transfer process (Sean and Nicole are testing this sometime before Tuesday PM)
- Check for single-file tools like the station dropping tool

A comment I have for next year's task list: Maybe split this task into the different computers: Metis, and then all the wheelhouse/marport/globe computers. 

I think we can mark this as "Done" when Gary is satisfied and has cloned it. Still need to talk to him about the upstairs computer.

**Comment by MargaretSiple-NOAA** [comment]
Metis computer update (from Sean):

Where things stand:

- Emily prepared an advanced version of the GAPsurvey package and I finished installing all of the software on the catch computer yesterday morning. Em may need to test some individual functions/features early next week.
- Megsie and Sarah checked the list of software installed, tested Bluetooth file transfer, and Metis without any problems.
- I tested Metis and the CTD conversion functions in GAPsurvey without any problems.
- The SeaBird software and drivers are installed for connecting the CTD to the catch computer but the CTD connection, setup, etc. have not tested them. Nicole and I attempted to get to it yesterday but, unsurprisingly, there was a ton of demand for testing. There is an old SBE 19 (non-plus) CTD in my office that could potentially be used for testing and I think Nicole and/or Bethany may be planning to try it out early next week ahead of the in person haul data training (?). Note: I'm guessing the xmlcon file is on the CD that was in the CTD crate.
- The survey app has not been added, but may need to be added by Tuesday. I can do that today if there is a final-ish version, but there may be some useful Bluetooth documentation missing from the current Survey App (Sarah is looking into it).

For next week:

- I think Duane (or someone else) still needs to test Portfolio and setup the directory structure for photos (?).
- Gary requests that GAP complete changes and testing to the golden image version finalized by COB on Tuesday (3/28).
- It sounds like Heather will clear test files after Tuesday.

Gaps:
- It sounds like we may not be able to test the catch computer with SBE19plus V2 CTDs before the field season and won't have config files pre-loaded. Should not be a big deal because we'll still have the laptops and some folks will probably continue to use the laptops due to vessel configuration.
- Anything else...?
- Overall, it sounds like the people who have tested the catch computer after the additional software was added have not had any issues with Metis loading, editing, backup, or extraction. Hopefully this helps clarify the current status of the catch computer for everyone!
