### ISSUE TITLE
Loading of apps on tablets

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-Survey-Planning#67]
Megsie notes for this year and next:

Need to do before April training. 
This task involves loading the .apk files onto all the tablets. Jerry can show us how to do this; in the past we have done it during the tablet training sessions too. We will need apk files for:
- crab app
- stomach app
- length app
- specimen app
- catch app

We need to amke sure we have the most current version of each of them, then load them onto all the tablets going on the survey. All tablets should get all the apps. This task takes a while and helps to have helpers.

**Comment by MargaretSiple-NOAA** [comment]
Update! I scheduled a meeting w Sarah on Thursday 3/30 to load apps onto ~25 tablets. The tablets are in Jerry's office next to his desk, along with charging cables and a splitter thingy. We need to:
1. Load new APKs from [here ](https://drive.google.com/drive/folders/1--6N4oAmIVMm4lHPPm4_DIKm7ByTwT61?usp=share_link). Jerry suggests using cords instead of Bluetooth.
3. If tablets are brand new and don't have TC, download it from the google apps store using login that I have. We may want to use a hotspot to access the app store. 
5. Install the apps and move them and total commander to the Shortcuts screen
2. Test moving raw data files to Metis computer - using MyFiles or Total Commander
3. When satisfied, delete data files from tablets and put the tablets in Jerry's office under the table w the mugs.

It should take a couple hours. I have scheduled 1-3 pm.

**Comment by MargaretSiple-NOAA** [comment]
All the 23 tablets that Jerry left for Sarah and I are loaded with the most recent 2023 version of all the survey apps. They're in my office. 

I need help with testing them out and installing Total Commander on them, though! 

Tracking spreadsheet for the tablets [here](https://docs.google.com/spreadsheets/d/1vfNl4OOH-dp27M82BLtj2snFChs_cSVeRb6TNtgBavE/edit?usp=sharing). Going to pick this up again tomorrow afternoon.

**Comment by SarahFriedman-NOAA** [comment]
Thank you so much, Megsie! I'll be around next week to help out with the rest.

**Comment by MargaretSiple-NOAA** [comment]
OK all the tablets now have survey apps, Total Commander, and have been set to the main tablet settings in the tablet setup doc (display sleep at 5 mins, etc). In-app settings haven't been modified because we don't know if these tablets will be on the Bering or GOA-AI survey. Thank you @nwraring and Jerry for helping out today! 

I am putting all finished tablets in Jerry's office.

In case more tablets need to be set up, [here ](https://docs.google.com/document/d/1m0ZNNzLw6JmH8VYdBFIcNmn2ubW50xJFmIjV-hVwwR4/edit?usp=sharing)are instructions I wrote based on what we did.
