### ISSUE TITLE
Testing applications

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-Survey-Planning#70]

**Comment by coleary-noaa** [comment]
@Ned-Laman-NOAA @bethanyriggle is this to test wheelhouse/calypso on the wheelhouse computers after Gary uploads and Megsie/Gary double check all is there?

**Comment by Ned-Laman-NOAA** [comment]
This was intended to cover the testing of Wheelhouse/Calypso before Gary cloned the "golden image" machine to distribute to the vessels. 
That aspect is done now. 
There is now an unanticipated round of testing going on (starting this afternoon I believe) to test peripheral applications (e.g., R software, Portfolio, etc) on the Metis machines and to further test whether Metis/GIDES on those seagoing machines still works with the peripheral software added to the machine. I'm including this here for future information about how we may want to expand this Task to include this new aspect that just became apparent. 
If this doesn't make sense, ask questions and I'll try to clarify. 
I'll leave Testing Applications "in progress" for now until we hear what goes down with the Metis/GIDES machine and the peripherals

**Comment by MargaretSiple-NOAA** [comment]
Sounds good Ned. Sean and I have a Metis machine (not yet cloned) in our office so I'll try out the peripheral apps and see if it breaks Metis. I don't anticipate that it will.

**Comment by MargaretSiple-NOAA** [comment]
Changed this from **Done** back to **In Progress** because of today's issues with Wheelhouse (same issue as in 2019). 

Metis testing and peripheral software on Metis computer look good apart from a couple final tasks, which are covered in #6. Suggest that Metis part is done (apart from Heather removing test files on Metis computer pre-cloning, and possible update of survey app on Metis computer) and that Wheelhouse/Calypso part is highest priority to sort out. @Ned-Laman-NOAA let us know when we can help out with that part.

## Suggestion for task list for next year
Distinguish this task from #6 . Suggest splitting software and software testing into Metis and Wheelhouse/Marport computers.

**Comment by Ned-Laman-NOAA** [comment]
For the Wheelhouse/Calypso software and testing. High priority is to try and reproduce the errors we were seeing this morning. I have Gary putting the master computer back up in the rack so I can run some test tows tomorrow to try and reproduce error. The original Python workaround was designed for this Windows 7 environment and this version of Wheelhouse so it should work IF we can find the original files to support it. They were on a Google Drive belonging to Alison that is no longer available. There's a chance that the files are on the master computer already and I'll check it tomorrow. If not, we need to check with Heather or OFIS to see if we can recover the contents of the Google Drive Alison refers to her in her marpDataFix instructions. As for other software on the Wheelhouse computers, we need to install the FFB directory on all GOA Wheelhouse machines with they're available and FFB is complete. This might have to be in Dutch. If we can recover the marpDataFix tool, it should be cloned with all Wheelhouse machines so that the Bering has access to the tool at sea too.
